export const MAX_HEALTH_BYTES = 64 * 1024;
export const MAX_MANIFEST_BYTES = 1024 * 1024;
export const MAX_WIDGET_BYTES = 16 * 1024 * 1024;
export const MAX_SNAPSHOT_BYTES = 512 * 1024 * 1024;

const MANDATORY_CURRENT_WIDGET_RESPONSES = 4;
export const MAX_RETAINED_RESPONSE_MULTIPLIER = 3;

export const MAX_RETAINED_BYTES = Math.floor(
  (MAX_SNAPSHOT_BYTES -
    MAX_HEALTH_BYTES -
    MAX_MANIFEST_BYTES -
    MANDATORY_CURRENT_WIDGET_RESPONSES * MAX_WIDGET_BYTES) /
    MAX_RETAINED_RESPONSE_MULTIPLIER
);
